# yaml-language-server: $schema=../../../../external/riscv-unified-db/spec/schemas/config_schema.json
---
$schema: config_schema.json#
kind: architecture configuration
type: fully configured
name: lynn-rv32I
description: The rv32I configuration of Lynn SoC project chip
implemented_extensions:
  - { name: I, version: ">= 2.1" }
  - { name: Sm, version: ">= 1.11.0" }
  - { name: Smhpm, version: ">= 1.11.0" }
  - { name: Zicntr, version: ">= 2.0" }
  - { name: Zicsr, version: ">= 2.0" }
  - { name: Zihpm, version: ">= 2.0" }

params:
  # Zicntr params
  TIME_CSR_IMPLEMENTED: true
  # Sm params
  MXLEN: 32
  PRECISE_SYNCHRONOUS_EXCEPTIONS: true
  TRAP_ON_ECALL_FROM_M: true
  TRAP_ON_EBREAK: true
  MARCHID_IMPLEMENTED: true
  ARCH_ID_VALUE: 0x24
  MIMPID_IMPLEMENTED: true
  IMP_ID_VALUE: 0x100
  VENDOR_ID_BANK: 0xC
  VENDOR_ID_OFFSET: 0x2
  MISALIGNED_LDST: false
  MISALIGNED_LDST_EXCEPTION_PRIORITY: low
  TRAP_ON_ILLEGAL_WLRL: false
  TRAP_ON_UNIMPLEMENTED_INSTRUCTION: true
  TRAP_ON_RESERVED_INSTRUCTION: true
  TRAP_ON_UNIMPLEMENTED_CSR: true
  REPORT_VA_IN_MTVAL_ON_BREAKPOINT: true
  REPORT_VA_IN_MTVAL_ON_LOAD_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_LOAD_ACCESS_FAULT: true
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_ACCESS_FAULT: true
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_ACCESS_FAULT: true
  REPORT_ENCODING_IN_MTVAL_ON_ILLEGAL_INSTRUCTION: true
  MTVAL_WIDTH: 32
  PMA_GRANULARITY: 3
  PHYS_ADDR_WIDTH: 32
  M_MODE_ENDIANNESS: little
  MISA_CSR_IMPLEMENTED: true
  MTVEC_ACCESS: rw
  MTVEC_MODES: [0, 1]
  MTVEC_BASE_ALIGNMENT_DIRECT: 4
  MTVEC_BASE_ALIGNMENT_VECTORED: 4
  MTVEC_ILLEGAL_WRITE_BEHAVIOR: retain
  # Smhpm params
  COUNTINHIBIT_EN: [
      false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false
    ]
  # Zihpm params
  HPM_COUNTER_EN: [
      false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false
    ]
  HPM_EVENTS: []
