name: lynn-rv32I
#compiler_exe: /opt/riscv/bin/riscv64-unknown-elf-gcc # executable name on $PATH or full path to executable
#objdump_exe: /opt/riscv/bin/riscv64-unknown-elf-objdump # executable name on $PATH or full path to executable, optional
compiler_exe: clang
objdump_exe: llvm-objdump
ref_model_exe: /opt/riscv/bin/sail_riscv_sim # executable name on $PATH or full path to executable
ref_model_type: sail # sail or spike
udb_config: lynn-rv32I.yaml
linker_script: link.ld
dut_include_dir: . # Directory containing DUT specific rvmodel_macros.h header
